# Generated by Django 5.2.5 on 2025-08-26 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitacionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('habitacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='habitaciones.habitacion')),
            ],
        ),
    ]
