# Generated by Django 5.2.5 on 2025-08-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_habitacionstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HabitacionStock',
        ),
    ]
