# Generated by Django 5.2.5 on 2025-08-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_delete_habitacionstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='planes/'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='promociones/'),
        ),
    ]
