# Generated by Django 5.2.6 on 2025-09-09 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_plan_imagen_promocion_imagen'),
        ('habitaciones', '0002_habitacion_stock_alter_habitacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='habitacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='habitaciones.habitacion'),
            preserve_default=False,
        ),
    ]
