

services:
  web:
    build: .
    command: ./wait_for_db.sh python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mariadb:11
    environment:
      MYSQL_DATABASE: hotel_db
      MYSQL_USER: hotel_user
      MYSQL_PASSWORD: hotel_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
