
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db

  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_DATABASE: hotel_db
      MYSQL_USER: hotel_user
      MYSQL_PASSWORD: hotel_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
