# Generated by Django 5.2.6 on 2025-09-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('simple', 'Simple'), ('doble', 'Doble'), ('suite', 'Suite'), ('presidencial', 'presidencial')], max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='habitaciones/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('capacidad', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
