# Generated by Django 5.2.5 on 2025-08-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('simple', 'Simple'), ('doble', 'Doble'), ('suite', 'Suite'), ('presidencial', 'presidencial')], max_length=100),
        ),
    ]
