# Generated by Django 5.2.6 on 2025-09-23 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_tipohabitacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'ordering': ['numero'], 'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipohabitacion',
            options={'verbose_name': 'Tipo de Habitación', 'verbose_name_plural': 'Tipos de Habitaciones'},
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='en_mantenimiento',
            field=models.BooleanField(default=False, help_text='Si la habitación está en mantenimiento'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones específicas de esta habitación', null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='habitaciones.tipohabitacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='stock_disponible',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible para reservar'),
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='stock_total',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad total de habitaciones de este tipo'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='disponible',
            field=models.BooleanField(default=True, help_text='Si la habitación está disponible para uso'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.CharField(help_text='Número o identificador de la habitación', max_length=10, unique=True),
        ),
    ]
