# Generated by Django 5.2.6 on 2025-09-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_habitacion_stock_alter_habitacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='capacidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
