# Generated by Django 5.2.6 on 2025-09-23 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.AddField(
            model_name='profile',
            name='block_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Razón del bloqueo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de bloqueo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_users', to=settings.AUTH_USER_MODEL, verbose_name='Bloqueado por'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Usuario bloqueado'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Última IP'),
        ),
    ]
