# Generated by Django 5.2.6 on 2025-09-17 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('habitaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
                ('dni', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('confirmada', models.BooleanField(default=False)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Crédito')], max_length=20, null=True)),
                ('token', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('cantidad_huespedes', models.PositiveIntegerField(default=1)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.habitacion')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.plan')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.promocion')),
                ('servicios', models.ManyToManyField(blank=True, to='administracion.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_reserva'],
            },
        ),
        migrations.CreateModel(
            name='HuespedActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_checkin', models.DateField(blank=True, null=True)),
                ('fecha_checkout', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habitaciones.habitacion')),
                ('huesped', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activo', to='reservas.huesped')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huespedes_activos', to='reservas.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='huesped',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huespedes', to='reservas.reserva'),
        ),
    ]
