# Generated by Django 5.2.5 on 2025-08-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_delete_habitacionstock'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='servicio',
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='administracion.servicio'),
        ),
    ]
