# Generated by Django 5.2.6 on 2025-09-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='activada',
            field=models.BooleanField(default=False),
        ),
    ]
