# Generated by Django 5.2.5 on 2025-08-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva']},
        ),
    ]
