# Generated by Django 5.2.6 on 2025-09-23 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_alter_habitacion_options_and_more'),
        ('reservas', '0002_reserva_activada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='activada',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='confirmada',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='habitacion',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidad_habitaciones',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de habitaciones reservadas'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='habitacion_asignada',
            field=models.ForeignKey(blank=True, help_text='Habitación específica asignada al hacer check-in', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habitaciones.habitacion'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_habitacion',
            field=models.ForeignKey(default=4343, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='habitaciones.tipohabitacion'),
            preserve_default=False,
        ),
    ]
