# Generated by Django 5.2.6 on 2025-09-14 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
