# Generated by Django 5.2.6 on 2025-09-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_options_remove_reserva_activada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Crédito'), ('mercadopago', 'MercadoPago'), ('paypal', 'PayPal'), ('crypto', 'Criptomonedas'), ('transferencia', 'Transferencia Bancaria')], max_length=20, null=True),
        ),
    ]
