# Generated by Django 5.2.6 on 2025-09-15 20:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True),
        ),
    ]
