# Generated by Django 5.2.6 on 2025-09-15 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_habitacion_capacidad'),
        ('reservas', '0004_alter_reserva_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuespedActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_checkin', models.DateField(blank=True, null=True)),
                ('fecha_checkout', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habitaciones.habitacion')),
                ('huesped', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activo', to='reservas.huesped')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huespedes_activos', to='reservas.reserva')),
            ],
        ),
    ]
